### ISSUE TITLE
vague instructions

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/js-templates-advanced-templating-lab#1]
Setting up recipeFormPartial isn't explained much.

Also, there isn't much exposure to what needs to be done in order to initialize previous to this lab, so this isn't very helpful: "Put any Handlebars registration code and page initialization code you need inside this function"

**Comment by maxwellbenton** [comment]
Hi @d-d-d-dalia,

Thank you for reporting this issue. We are currently reviewing our JavaScript materials, have documented this as a known issue for the templating section and will resolve it in an upcoming update.

Thank you for contributing to a learn.co repository!
