### ISSUE TITLE
Test results do not show properly

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/js-templates-advanced-templating-lab#11]
Running `learn` results in one of these two error messages:

```
> java-script-handlebars-templates-lab@0.1.0 test /Users/ian/technical-coach/js-templates-advanced-templating-lab-v-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 0   -_-_-_-_-__,------,
 9   -_-_-_-_-__|  /\_/\
 0   -_-_-_-_-_~|_( x .x)
     -_-_-_-_-_ ""  ""
npm ERR! Test failed.  See above for more details.
```
(Error message details are not shown)

```
/Users/brittanygrebnova/.rvm/gems/ruby-2.3.3/gems/learn-test-2.6.1/lib/learn_test/strategies/mocha.rb:42:in results': undefined method []' for nil:NilClass (NoMethodError)
```

The student who reported this was using a local environment, and I reproduced the issue in my local environment as well. I also noticed that NPM identified several packages with vulnerabilities, and fixing those did not change the result.

Reported by @brittanygrebnova.

**Comment by sgharms** [comment]
We are planning on removing this lab due to these issues. Removal is pending decision from Ashlee Scott, but we know this is problematic.
