### ISSUE TITLE
Multiple IDs with the same name?

### ISSUE THREAD

**Issue by AAM77** [learn-co-curriculum/js-templates-advanced-templating-lab#6]
**TL&DR:** We shouldn't use labels for id="" in more than one place (i.e. they should be unique). This lab's README and test-code does not abide by this rule. I made changes to my lab to address this in my code, the test-code, and the README. I think the test-code and README should be permanently changed to have unique ids for the HTML markup. Please read the full text below to get a complete idea of what I am talking about.

Hi,

I hope this finds everyone in good health.

My main concern for this particular post is that the content of both the current README and index-test.js files require students to assign multiple HTML markup IDs with 'name' and 'description' (first in the recipe form and again in (1) the recipe-template and (2) the recipe-details-partial). Even the tests are coded to search for the 'name' and 'description' ids in these locations.

This is not okay, in my opinion, especially when students are taught throughout the course that an id="" is supposed to be unique and used only once. For multiple uses, we have class="" and name="". When encouraging good practice, the labs should be updated to reflect this. In a teaching environment it should be a "lead by example" scenario, not a "do as I say, not as I do" mindset. Otherwise, it is simply confusing and diminishes the emphasis on good practice.

In any case, I could not let this stand for my own lab, so I made the appropriate changes to address the issues I have mentioned above. I replaced the 'name' and 'description' ids for the recipe-template and recipe-details-partial template to be 'recipeName' and 'recipeDescription', respectively. This meant changing the respective labels inside of the index-test.js file as well.

I did not make any changes beyond this.

I hope this was okay because the change was minor and did not affect the skill and knowledge the test-code was meant to test.

You can confirm this by taking a look at the changes I made by visiting the repository on my page:
https://github.com/AAM77/js-templates-advanced-templating-lab-v-000

OR

The commits depicting the changes I made are as follows:

6afe7380c0aaba7cc17ccced26d9b041fcf0513c
2fed6ae3824473b4a65ef4ff3a1139f523814e47
1f6bae02ef838c3d278ec5cba4adf51c8f85e5e5

(I decided to make some of the changes & commits after I began writing this post.)

Thank you for taking the time to read this. You are, of course, free to disagree and make no changes. The purpose of this post was to bring it to your attention and back my reasons for doing so with a proper explanation.

**Comment by sgharms** [comment]
We're going to peer review  a change to the ids per your recommendation. Thanks.
