### ISSUE TITLE
Tests do not work with updated software

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/js-templates-advanced-templating-lab#9]
It is probably a bad idea to have tests that are incompatible with updated versions of node. If the tests aren't going to be updated, there should be a walkthrough of nvm on local machines provided. There were some tests previously as well that were incompatible with newer JS syntax ie `newObject = {...oldObject, appedingObject};`. As it is now, if you are working with a newer version of Node, you spend more time figuring out why the tests aren't working than doing the lesson.

**Comment by drakeltheryuujin** [comment]
Hi @micahshute,
We’ve built your feedback into our next major release of this section of curriculum. We’re targeting delivery in the first half of 2019.
